on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: Build & Release

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest  # Specify Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'  # Adjust version as needed

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*
            build/windows/runner/Release/*
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
